# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "ocean"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = false
footer.showScrollToTop = false
footer.showThemeAttribution = false
footer.showAppearanceSwitcher = true
header.layout = "hamburger"

[homepage]
  layout = "profile" # valid options: page, profile, custom
  showRecent = false

[article]
  showDate = false
  showAuthor = false
  showBreadcrumbs = false
  showDraftLabel = false
  showEdit = false
  editURL = "https://github.com/AntoineSoetewey/antoinesoetewey.com/"
  editAppendPath = true
  showHeadingAnchors = false
  showPagination = false
  showReadingTime = false
  # sharingLinks = ["facebook", "twitter", "pinterest", "reddit", "linkedin", "email"]

[list]
  showBreadcrumbs = false
  showSummary = false
  groupByYear = false

[taxonomy]
  showTermCount = true

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
